apiVersion: apps/v1
kind: Deployment
metadata:
  name: tams-api
  namespace: tams
  labels:
    app: tams-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tams-api
  template:
    metadata:
      labels:
        app: tams-api
        version: v1
    spec:
      serviceAccountName: tams-api-sa
      containers:
      - name: tams-api
        image: tams-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        # VAST Database credentials (secrets)
        - name: VAST_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tams-secrets
              key: vast-access-key
        - name: VAST_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tams-secrets
              key: vast-secret-key
        
        # S3 Storage credentials (secrets)
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tams-secrets
              key: s3-access-key-id
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tams-secrets
              key: s3-secret-access-key
        
        volumeMounts:
        - name: tams-config
          mountPath: /etc/tams
          readOnly: true
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      
      volumes:
      - name: tams-config
        configMap:
          name: tams-config
      
      restartPolicy: Always
      securityContext:
        fsGroup: 1000 