version: '3.8'

services:
  tams-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - vast_data:/app/vast_data
      - ./config/production.json:/etc/tams/config.json:ro  # Mount config file
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tams-network

volumes:
  vast_data:
    driver: local

networks:
  tams-network:
    driver: bridge
