connector.name=vast
endpoint=http://main.selab-var204.selab.vastdata.com
region=us-east-1
access_key_id=SRSPW0DQT9T70Y787U68
secret_access_key=WkKLxvG7YkAdSMuHjFsZG5/BhDk9Ou7BS1mDQGnr

# Preliminary tuning parameters
num_of_splits=64
num_of_subsplits=10
vast.http-client.request-timeout=60m
vast.http-client.idle-timeout=60m

data_endpoints=http://main.selab-var204.selab.vastdata.com

vast.http-client.request-timeout=100h
vast.http-client.idle-timeout=290s
vast.http-client.max-connections=100
vast.http-client.max-connections-per-server=50
