{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tams.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tams.labels" . | nindent 4 }}
type: Opaque
data:
  vast-access-key: {{ .Values.secrets.vastAccessKey | b64enc | quote }}
  vast-secret-key: {{ .Values.secrets.vastSecretKey | b64enc | quote }}
  s3-access-key-id: {{ .Values.secrets.s3AccessKeyId | b64enc | quote }}
  s3-secret-access-key: {{ .Values.secrets.s3SecretAccessKey | b64enc | quote }}
{{- end }} 